language: cpp
compiler:
  - gcc
before_install:
  - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
  - tar --bzip2 -xf boost_1_55_0.tar.bz2
  - cd boost_1_55_0 && ./bootstrap.sh --with-libraries=filesystem,serialization,system && ./b2 install --prefix=$HOME/boost --toolset=gcc >build.log 2>&1 && cd ..
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - valgrind
    - libgtest-dev
os:
  - linux
  - osx
script:
  - mkdir build
  - cd build
  - export BOOST_ROOT=$HOME/boost
  - cmake ..
  - make
  - make test
notifications:
  recipients:
    - service@braintwister.eu
  email:
    on_success: change
    on_failure: always
sudo: false
