language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install doxygen
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
notifications:
  recipients:
    - info@braintwister.eu
  email:
    on_success: change
    on_failure: always
